Data manipulation and Analysis with Pandas

data manipulation and analysis are key tasks in any data science or data analysis project. Pandas provides a wide range of functions for data manipulation and analysis, making it easier to clean, transform and extract insights from data. In this lession , we will cover various data manipulation and analysis techniques using Pandas.

In [40]:
import pandas as pd

df = pd.read_csv('company-sales.csv')
print(df)

    month_number  facecream  facewash  toothpaste  bathingsoap  shampoo  \
0              1       2500      1500        5200         9200     1200
1              2       2630      1200        5100         6100     2100
2              3       2140      1340        4550         9550     3550
3              4       3400      1130        5870         8870     1870
4              5       3600      1740        4560         7760     1560
5              6       2760      1555        4890         7490     1890
6              7       2980      1120        4780         8980     1780
7              8       3700      1400        5860         9960     2860
8              9       3540      1780        6100         8100     2100
9             10       1990      1890        8300        10300     2300
10            11       2340      2100        7300        13300     2400
11            12       2900      1760        7400        14400     1800

    moisturizer  total_units  total_profit
0          1500        21100        211000
1          1200        18330        183300
2          1340        22470        224700
3          1130        22270        222700
4          1740        20960        209600
5          1555        20140        201400
6          1120        29550        295500
7          1400        36140        361400
8          1780        23400        234000
9          1890        26670        266700
10         2100        41280        412800
11         1760        30020        300200

In [4]:
df.head(10)

,month_number,facecream,facewash,toothpaste,bathingsoap,shampoo,moisturizer,total_units,total_profit
0,1,2500,1500,5200,9200,1200,1500,21100,211000
1,2,2630,1200,5100,6100,2100,1200,18330,183300
2,3,2140,1340,4550,9550,3550,1340,22470,224700
3,4,3400,1130,5870,8870,1870,1130,22270,222700
4,5,3600,1740,4560,7760,1560,1740,20960,209600
5,6,2760,1555,4890,7490,1890,1555,20140,201400
6,7,2980,1120,4780,8980,1780,1120,29550,295500
7,8,3700,1400,5860,9960,2860,1400,36140,361400
8,9,3540,1780,6100,8100,2100,1780,23400,234000
9,10,1990,1890,8300,10300,2300,1890,26670,266700

In [5]:
df.tail(5)

,month_number,facecream,facewash,toothpaste,bathingsoap,shampoo,moisturizer,total_units,total_profit
7,8,3700,1400,5860,9960,2860,1400,36140,361400
8,9,3540,1780,6100,8100,2100,1780,23400,234000
9,10,1990,1890,8300,10300,2300,1890,26670,266700
10,11,2340,2100,7300,13300,2400,2100,41280,412800
11,12,2900,1760,7400,14400,1800,1760,30020,300200

In [6]:
df.describe()

,month_number,facecream,facewash,toothpaste,bathingsoap,shampoo,moisturizer,total_units,total_profit
count,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.00000,12.000000
mean,6.500000,2873.333333,1542.916667,5825.833333,9500.833333,2117.500000,1542.916667,26027.50000,260275.000000
std,3.605551,584.595172,316.733745,1242.032486,2348.095779,617.724931,316.733745,7014.36594,70143.659404
min,1.000000,1990.000000,1120.000000,4550.000000,6100.000000,1200.000000,1120.000000,18330.00000,183300.000000
25%,3.750000,2460.000000,1305.000000,4862.500000,8015.000000,1795.000000,1305.000000,21065.00000,210650.000000
50%,6.500000,2830.000000,1527.500000,5530.000000,9090.000000,1995.000000,1527.500000,22935.00000,229350.000000
75%,9.250000,3435.000000,1765.000000,6400.000000,10045.000000,2325.000000,1765.000000,29667.50000,296675.000000
max,12.000000,3700.000000,2100.000000,8300.000000,14400.000000,3550.000000,2100.000000,41280.00000,412800.000000

In [7]:
df.dtypes

month_number    int64
facecream       int64
facewash        int64
toothpaste      int64
bathingsoap     int64
shampoo         int64
moisturizer     int64
total_units     int64
total_profit    int64
dtype: object

In [8]:
## handling missing vales
df.isnull()

,month_number,facecream,facewash,toothpaste,bathingsoap,shampoo,moisturizer,total_units,total_profit
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False

In [9]:
df.isnull().any(axis=1)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
dtype: bool

In [ ]:
df.isnull().sum() ## none of them having True (missing values)

month_number    0
facecream       0
facewash        0
toothpaste      0
bathingsoap     0
shampoo         0
moisturizer     0
total_units     0
total_profit    0
dtype: int64

In [13]:
## if there is any missing values and youy have to fill then use
df_filled = df.fillna(0)
print(df_filled)

    month_number  facecream  facewash  toothpaste  bathingsoap  shampoo  \
0              1       2500      1500        5200         9200     1200
1              2       2630      1200        5100         6100     2100
2              3       2140      1340        4550         9550     3550
3              4       3400      1130        5870         8870     1870
4              5       3600      1740        4560         7760     1560
5              6       2760      1555        4890         7490     1890
6              7       2980      1120        4780         8980     1780
7              8       3700      1400        5860         9960     2860
8              9       3540      1780        6100         8100     2100
9             10       1990      1890        8300        10300     2300
10            11       2340      2100        7300        13300     2400
11            12       2900      1760        7400        14400     1800

    moisturizer  total_units  total_profit
0          1500        21100        211000
1          1200        18330        183300
2          1340        22470        224700
3          1130        22270        222700
4          1740        20960        209600
5          1555        20140        201400
6          1120        29550        295500
7          1400        36140        361400
8          1780        23400        234000
9          1890        26670        266700
10         2100        41280        412800
11         1760        30020        300200

In [16]:
## filled missing values with the mean of the column
df['Sales_fillNA'] = df['facecream'].fillna(df['facecream'].mean())
df

,month_number,facecream,facewash,toothpaste,bathingsoap,shampoo,moisturizer,total_units,total_profit,Sales_fillNA
0,1,2500,1500,5200,9200,1200,1500,21100,211000,2500
1,2,2630,1200,5100,6100,2100,1200,18330,183300,2630
2,3,2140,1340,4550,9550,3550,1340,22470,224700,2140
3,4,3400,1130,5870,8870,1870,1130,22270,222700,3400
4,5,3600,1740,4560,7760,1560,1740,20960,209600,3600
5,6,2760,1555,4890,7490,1890,1555,20140,201400,2760
6,7,2980,1120,4780,8980,1780,1120,29550,295500,2980
7,8,3700,1400,5860,9960,2860,1400,36140,361400,3700
8,9,3540,1780,6100,8100,2100,1780,23400,234000,3540
9,10,1990,1890,8300,10300,2300,1890,26670,266700,1990
10,11,2340,2100,7300,13300,2400,2100,41280,412800,2340
11,12,2900,1760,7400,14400,1800,1760,30020,300200,2900

In [17]:
df.dtypes

month_number    int64
facecream       int64
facewash        int64
toothpaste      int64
bathingsoap     int64
shampoo         int64
moisturizer     int64
total_units     int64
total_profit    int64
Sales_fillNA    int64
dtype: object

In [18]:
# renaming the columns

df = df.rename(columns={'month_number':'Month'})
df

,Month,facecream,facewash,toothpaste,bathingsoap,shampoo,moisturizer,total_units,total_profit,Sales_fillNA
0,1,2500,1500,5200,9200,1200,1500,21100,211000,2500
1,2,2630,1200,5100,6100,2100,1200,18330,183300,2630
2,3,2140,1340,4550,9550,3550,1340,22470,224700,2140
3,4,3400,1130,5870,8870,1870,1130,22270,222700,3400
4,5,3600,1740,4560,7760,1560,1740,20960,209600,3600
5,6,2760,1555,4890,7490,1890,1555,20140,201400,2760
6,7,2980,1120,4780,8980,1780,1120,29550,295500,2980
7,8,3700,1400,5860,9960,2860,1400,36140,361400,3700
8,9,3540,1780,6100,8100,2100,1780,23400,234000,3540
9,10,1990,1890,8300,10300,2300,1890,26670,266700,1990
10,11,2340,2100,7300,13300,2400,2100,41280,412800,2340
11,12,2900,1760,7400,14400,1800,1760,30020,300200,2900

In [20]:
## changing the datatypes

df['New_facecream'] = df['facecream'].astype(float)
df

,Month,facecream,facewash,toothpaste,bathingsoap,shampoo,moisturizer,total_units,total_profit,Sales_fillNA,New_facecream
0,1,2500,1500,5200,9200,1200,1500,21100,211000,2500,2500.0
1,2,2630,1200,5100,6100,2100,1200,18330,183300,2630,2630.0
2,3,2140,1340,4550,9550,3550,1340,22470,224700,2140,2140.0
3,4,3400,1130,5870,8870,1870,1130,22270,222700,3400,3400.0
4,5,3600,1740,4560,7760,1560,1740,20960,209600,3600,3600.0
5,6,2760,1555,4890,7490,1890,1555,20140,201400,2760,2760.0
6,7,2980,1120,4780,8980,1780,1120,29550,295500,2980,2980.0
7,8,3700,1400,5860,9960,2860,1400,36140,361400,3700,3700.0
8,9,3540,1780,6100,8100,2100,1780,23400,234000,3540,3540.0
9,10,1990,1890,8300,10300,2300,1890,26670,266700,1990,1990.0
10,11,2340,2100,7300,13300,2400,2100,41280,412800,2340,2340.0
11,12,2900,1760,7400,14400,1800,1760,30020,300200,2900,2900.0

In [21]:
## apply function in any column

df['New_facewash'] = df['facewash'].apply(lambda x:x/100)
df.head()

,Month,facecream,facewash,toothpaste,bathingsoap,shampoo,moisturizer,total_units,total_profit,Sales_fillNA,New_facecream,New_facewash
0,1,2500,1500,5200,9200,1200,1500,21100,211000,2500,2500.0,15.0
1,2,2630,1200,5100,6100,2100,1200,18330,183300,2630,2630.0,12.0
2,3,2140,1340,4550,9550,3550,1340,22470,224700,2140,2140.0,13.4
3,4,3400,1130,5870,8870,1870,1130,22270,222700,3400,3400.0,11.3
4,5,3600,1740,4560,7760,1560,1740,20960,209600,3600,3600.0,17.4

In [22]:
## Data Aggregating and Grouping

df.head()

,Month,facecream,facewash,toothpaste,bathingsoap,shampoo,moisturizer,total_units,total_profit,Sales_fillNA,New_facecream,New_facewash
0,1,2500,1500,5200,9200,1200,1500,21100,211000,2500,2500.0,15.0
1,2,2630,1200,5100,6100,2100,1200,18330,183300,2630,2630.0,12.0
2,3,2140,1340,4550,9550,3550,1340,22470,224700,2140,2140.0,13.4
3,4,3400,1130,5870,8870,1870,1130,22270,222700,3400,3400.0,11.3
4,5,3600,1740,4560,7760,1560,1740,20960,209600,3600,3600.0,17.4

In [26]:
df['Product']=['A','B','C','D','E','F','G','H','I','J','K','L']
df

,Month,facecream,facewash,toothpaste,bathingsoap,shampoo,moisturizer,total_units,total_profit,Sales_fillNA,New_facecream,New_facewash,Product
0,1,2500,1500,5200,9200,1200,1500,21100,211000,2500,2500.0,15.00,A
1,2,2630,1200,5100,6100,2100,1200,18330,183300,2630,2630.0,12.00,B
2,3,2140,1340,4550,9550,3550,1340,22470,224700,2140,2140.0,13.40,C
3,4,3400,1130,5870,8870,1870,1130,22270,222700,3400,3400.0,11.30,D
4,5,3600,1740,4560,7760,1560,1740,20960,209600,3600,3600.0,17.40,E
5,6,2760,1555,4890,7490,1890,1555,20140,201400,2760,2760.0,15.55,F
6,7,2980,1120,4780,8980,1780,1120,29550,295500,2980,2980.0,11.20,G
7,8,3700,1400,5860,9960,2860,1400,36140,361400,3700,3700.0,14.00,H
8,9,3540,1780,6100,8100,2100,1780,23400,234000,3540,3540.0,17.80,I
9,10,1990,1890,8300,10300,2300,1890,26670,266700,1990,1990.0,18.90,J
10,11,2340,2100,7300,13300,2400,2100,41280,412800,2340,2340.0,21.00,K
11,12,2900,1760,7400,14400,1800,1760,30020,300200,2900,2900.0,17.60,L

In [28]:
grouped_mean = df.groupby('Product')['facewash'].mean()
print(grouped_mean)

Product
A    1500.0
B    1200.0
C    1340.0
D    1130.0
E    1740.0
F    1555.0
G    1120.0
H    1400.0
I    1780.0
J    1890.0
K    2100.0
L    1760.0
Name: facewash, dtype: float64

In [30]:
grouped_sum = df.groupby(['Product', 'Month'])['total_units'].sum()
print(grouped_sum)

Product  Month
A        1        21100
B        2        18330
C        3        22470
D        4        22270
E        5        20960
F        6        20140
G        7        29550
H        8        36140
I        9        23400
J        10       26670
K        11       41280
L        12       30020
Name: total_units, dtype: int64

In [31]:
grouped_meann = df.groupby(['Product', 'Month'])['total_units'].mean()
print(grouped_meann)

Product  Month
A        1        21100.0
B        2        18330.0
C        3        22470.0
D        4        22270.0
E        5        20960.0
F        6        20140.0
G        7        29550.0
H        8        36140.0
I        9        23400.0
J        10       26670.0
K        11       41280.0
L        12       30020.0
Name: total_units, dtype: float64

In [33]:
## aggregate multiple functions

grouped_agg = df.groupby('Product')['total_profit'].agg(['mean', 'sum', 'count'])
grouped_agg

             mean     sum  count
Product
A        211000.0  211000      1
B        183300.0  183300      1
C        224700.0  224700      1
D        222700.0  222700      1
E        209600.0  209600      1
F        201400.0  201400      1
G        295500.0  295500      1
H        361400.0  361400      1
I        234000.0  234000      1
J        266700.0  266700      1
K        412800.0  412800      1
L        300200.0  300200      1

In [36]:
## merging and joining dataframes


## create sample DataFrames

df1 = pd.DataFrame({'key' : ['A','B','C'], 'Value1' : [1,2,3]})
df2 = pd.DataFrame({'key' : ['A', 'B', 'D'], 'Value2' : [4,5,6]})

In [37]:
df1

  key  Value1
0   A       1
1   B       2
2   C       3

In [38]:
df2

  key  Value2
0   A       4
1   B       5
2   D       6

In [46]:
## Merge dataframe on the 'Key Columns'

pd.merge(df1, df2, on='key', how='inner')

  key  Value1  Value2
0   A       1       4
1   B       2       5

In [48]:
pd.merge(df1, df2, on='key', how='outer')

  key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [49]:
pd.merge(df1, df2, on='key', how='left')

  key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [ ]:
pd.merge(df1, df2, on='key', how='right') ## right side (df2) will have high priority

  key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6