Pandas - DataFrame and Series

Pandas is a powerful data manipulation library in python,,widely used for data analysis and data cleaning. It provides primarly two data structures : Series and Dataframes. A series is one-dimensional array like object. while a DataFrame is a two-dimensional, size-mutuable , and  potentially heterogenous tabular data structure with labeled axes(rows and columns).

In [ ]:
! pip install pandas

In [1]:
import pandas as pd

In [2]:
## series
## a pandas series is a one-dimensional array-like object that can hold any data type. it is similar to a column in a table.

import pandas as pd
data = [1,2,3,4,5]
series = pd.Series(data)
print("Series", series)
print(type(series))

Series 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [3]:
## create a series from dictonary
data = {'a':1,'b':2,'c':3}
pd.Series(data)

a    1
b    2
c    3
dtype: int64

In [6]:
data = [10,20,30]
index = ['a','b','c']

pd.Series(data, index = index)


## so without using any key-values pair , how do i need to use this index over here

a    10
b    20
c    30
dtype: int64

In [4]:
## DataFrame
## create a Dataframe from a dictionary of a list

data = {
    'Name':['Pranav','Raj', 'Sheena'],
    'Age': ['21', '20', '21'],
    'City': ['Bangalore', 'New York', 'Delhi']
}

df = pd.DataFrame(data)
print(df)
print(type(df))

     Name Age       City
0  Pranav  21  Bangalore
1     Raj  20   New York
2  Sheena  21      Delhi
<class 'pandas.core.frame.DataFrame'>

In [9]:
# if i want to convert this in an array

import numpy as np

np.array(df)

array([['Pranav', '21', 'Bangalore'],
       ['Raj', '20', 'New York'],
       ['Sheena', '21', 'Delhi']], dtype=object)

In [17]:
## create a dataframe from a list of dictonary

data = [
    {'Name':'Pranav','Age': 32 , 'City' : 'Bangalore'},
    {'Name':'Avnish','Age': 20 , 'City' : 'Delhi'},
    {'Name':'Rutik','Age': 24 , 'City' : 'Pune'},
]

df = pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age       City
0  Pranav   32  Bangalore
1  Avnish   20      Delhi
2   Rutik   24       Pune
<class 'pandas.core.frame.DataFrame'>

In [16]:
df = pd.read_csv('company-sales.csv')
df.head(10)

,month_number,facecream,facewash,toothpaste,bathingsoap,shampoo,moisturizer,total_units,total_profit
0,1,2500,1500,5200,9200,1200,1500,21100,211000
1,2,2630,1200,5100,6100,2100,1200,18330,183300
2,3,2140,1340,4550,9550,3550,1340,22470,224700
3,4,3400,1130,5870,8870,1870,1130,22270,222700
4,5,3600,1740,4560,7760,1560,1740,20960,209600
5,6,2760,1555,4890,7490,1890,1555,20140,201400
6,7,2980,1120,4780,8980,1780,1120,29550,295500
7,8,3700,1400,5860,9960,2860,1400,36140,361400
8,9,3540,1780,6100,8100,2100,1780,23400,234000
9,10,1990,1890,8300,10300,2300,1890,26670,266700

In [19]:
## accessing Data from DataFrame

df

     Name  Age       City
0  Pranav   32  Bangalore
1  Avnish   20      Delhi
2   Rutik   24       Pune

In [23]:
type(df['Name'])
df['Name']

0    Pranav
1    Avnish
2     Rutik
Name: Name, dtype: object

In [30]:
df.loc[0][0]

## 0 -> row indexing

/var/folders/19/zyhh8v2d7dd5d5zmv5m5t4_m0000gn/T/ipykernel_55842/2766581127.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][0]

'Pranav'

In [27]:
df.iloc[1][0]

/var/folders/19/zyhh8v2d7dd5d5zmv5m5t4_m0000gn/T/ipykernel_55842/1019881219.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[1][0]

'Avnish'

In [33]:
## accessing a specified element

df.at[1,'Age']

np.int64(20)

In [34]:
df.at[2,'Name']

'Rutik'

In [35]:
df

     Name  Age       City
0  Pranav   32  Bangalore
1  Avnish   20      Delhi
2   Rutik   24       Pune

In [36]:
## accessing a specific element using iat

df.iat[2,2]

'Pune'

In [37]:
df

     Name  Age       City
0  Pranav   32  Bangalore
1  Avnish   20      Delhi
2   Rutik   24       Pune

In [38]:
## Data Manipulation with dataframe
df

     Name  Age       City
0  Pranav   32  Bangalore
1  Avnish   20      Delhi
2   Rutik   24       Pune

In [51]:
df['Salary'] = [20000, 40000, 60000]
df

     Name  Age       City  Salary
0  Pranav   32  Bangalore   20000
1  Avnish   20      Delhi   40000
2   Rutik   24       Pune   60000

In [ ]:
## remove a column

df.drop('Salary') # because bydefault it has axis = 0(rows) and row does not have any Salary field

KeyError: "['Salary'] not found in axis"

In [44]:
df

     Name  Age       City  Salary
0  Pranav   32  Bangalore   20000
1  Avnish   20      Delhi   40000
2   Rutik   24       Pune   60000

In [45]:
df.drop('Salary', axis = 1)

     Name  Age       City
0  Pranav   32  Bangalore
1  Avnish   20      Delhi
2   Rutik   24       Pune

In [46]:
df

     Name  Age       City  Salary
0  Pranav   32  Bangalore   20000
1  Avnish   20      Delhi   40000
2   Rutik   24       Pune   60000

In [52]:
# Now Salary column does not remove permantely even though we did drop that column

# to remove it permenteley we have to add inplace=True

df.drop('Salary', axis=1, inplace=True)

In [56]:
df

     Name  Age       City
0  Pranav   34  Bangalore
1  Avnish   22      Delhi
2   Rutik   26       Pune

In [57]:
## add age to the column

df['Age']= df['Age'] + 1
df

     Name  Age       City
0  Pranav   35  Bangalore
1  Avnish   23      Delhi
2   Rutik   27       Pune

In [ ]:
df.drop(0) # butnot a permenant solution

     Name  Age   City
1  Avnish   23  Delhi
2   Rutik   27   Pune

In [59]:
df

     Name  Age       City
0  Pranav   35  Bangalore
1  Avnish   23      Delhi
2   Rutik   27       Pune

In [61]:
df.drop(0, inplace=True)
df

     Name  Age   City
1  Avnish   23  Delhi
2   Rutik   27   Pune

In [62]:
df = pd.read_csv('company-sales.csv')
df.head(10)

,month_number,facecream,facewash,toothpaste,bathingsoap,shampoo,moisturizer,total_units,total_profit
0,1,2500,1500,5200,9200,1200,1500,21100,211000
1,2,2630,1200,5100,6100,2100,1200,18330,183300
2,3,2140,1340,4550,9550,3550,1340,22470,224700
3,4,3400,1130,5870,8870,1870,1130,22270,222700
4,5,3600,1740,4560,7760,1560,1740,20960,209600
5,6,2760,1555,4890,7490,1890,1555,20140,201400
6,7,2980,1120,4780,8980,1780,1120,29550,295500
7,8,3700,1400,5860,9960,2860,1400,36140,361400
8,9,3540,1780,6100,8100,2100,1780,23400,234000
9,10,1990,1890,8300,10300,2300,1890,26670,266700

In [ ]:
## Display the data types of each column

print('data type:\n', df.dtypes)

data type:
 month_number    int64
facecream       int64
facewash        int64
toothpaste      int64
bathingsoap     int64
shampoo         int64
moisturizer     int64
total_units     int64
total_profit    int64
dtype: object

In [64]:
## Describe the DataFrame

print('Statistical summary:\n', df.describe())

Statistical summary:
        month_number    facecream     facewash   toothpaste   bathingsoap  \
count     12.000000    12.000000    12.000000    12.000000     12.000000
mean       6.500000  2873.333333  1542.916667  5825.833333   9500.833333
std        3.605551   584.595172   316.733745  1242.032486   2348.095779
min        1.000000  1990.000000  1120.000000  4550.000000   6100.000000
25%        3.750000  2460.000000  1305.000000  4862.500000   8015.000000
50%        6.500000  2830.000000  1527.500000  5530.000000   9090.000000
75%        9.250000  3435.000000  1765.000000  6400.000000  10045.000000
max       12.000000  3700.000000  2100.000000  8300.000000  14400.000000

           shampoo  moisturizer  total_units   total_profit
count    12.000000    12.000000     12.00000      12.000000
mean   2117.500000  1542.916667  26027.50000  260275.000000
std     617.724931   316.733745   7014.36594   70143.659404
min    1200.000000  1120.000000  18330.00000  183300.000000
25%    1795.000000  1305.000000  21065.00000  210650.000000
50%    1995.000000  1527.500000  22935.00000  229350.000000
75%    2325.000000  1765.000000  29667.50000  296675.000000
max    3550.000000  2100.000000  41280.00000  412800.000000